channels:
  - pytorch
  - conda-forge

dependencies:
  - pytorch
  - scikit-learn
  - numpy
  - pandas
  - python=3.11
  - ipykernel
  - matplotlib
  - seaborn
  - cartopy
  - geopy
  - geopandas
  - dask
  - dask-geopandas
  - tqdm
  - rioxarray
  - pathlib
  - scipy
  - captum
  - pyarrow
  - fastparquet
  - gitpython
  - xgboost