channels:
  - rapidsai
  - conda-forge
  - nvidia

dependencies:
  - cuda-version=11.5
  - scikit-learn
  - numpy
  - pandas
  - python==3.11
  - ipykernel
  - matplotlib
  - seaborn
  - cartopy
  - geopy
  - geopandas
  - dask
  - dask-geopandas
  - tqdm
  - cudf
  - cuspatial
  - rioxarray
  - pathlib
  - pyarrow
  - fastparquet
  - gitpython